#include <uC++.h>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <vector>
#include <stdlib.h>
#include <iomanip>

using namespace std;

#define SodaCost                   1    //# Manufacturer Suggested Retail Price (MSRP) per bottle
#define NumStudents                4   // # number of students to create
#define MaxPurchases              10    //# maximum number of bottles a student purchases
#define NumVendingMachines         3    //# number of vending machines
#define MaxStockPerFlavour         5   // # maximum number of bottles of each flavour in a vending machine
#define MaxShippedPerFlavour       6   // # maximum number of bottles of each flavour generated by the bottling
                                //#    plant per production run
#define TimeBetweenShipments       5   // # length of time between shipment pickup
#define ParentalDelay             20   // # length of time between new deposits of funds
#define NumCouriers                3    //# maximum number of couriers in the pool

unsigned int seed;
